import { readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { light, dark, studyLight, studyDark } from '../packages/design-tokens/src/index';
const block = (selector: string, values: Record<string, string>) =>
  selector +
  ' {\n' +
  Object.entries(values)
    .map(([key, value]) => '  --' + key + ': ' + value + ';')
    .join('\n') +
  '\n}\n';
const header =
  '/* Generated by npm run tokens:build. Edit packages/design-tokens/src/index.ts. */\n';
const outputs = {
  'packages/design-tokens/tokens.css':
    header +
    block(':root', light) +
    '@media (prefers-color-scheme: dark) {\n' +
    block(':root:not(.light)', dark) +
    '}\n' +
    block(':root.dark', dark),
  'packages/design-tokens/study.css':
    header + '@layer base {\n' + block(':root', studyLight) + block('.dark', studyDark) + '}\n',
};
async function main() {
  for (const [path, css] of Object.entries(outputs)) {
    const output = await format(css, { ...(await resolveConfig(path)), parser: 'css' });
    if (process.argv.includes('--check')) {
      if (readFileSync(path, 'utf8') !== output)
        throw new Error(path + ' is stale; run npm run tokens:build');
    } else writeFileSync(path, output);
  }
}
void main();
